<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.util.List" %>
<%
if (session.getAttribute("staffID") == null) {
    response.sendRedirect(request.getContextPath() + "/login.jsp");
    return;
}
String period = (String) request.getAttribute("period");
String anchorDate = (String) request.getAttribute("anchorDate");
String startDate = (String) request.getAttribute("startDate");
String endDate = (String) request.getAttribute("endDate");
String generatedDate = (String) request.getAttribute("generatedDate");
String staffName = (String) session.getAttribute("staffName");
Integer paymentCount = (Integer) request.getAttribute("paymentCount");
Double totalRevenue = (Double) request.getAttribute("totalRevenue");
Integer expiringMemberCount = (Integer) request.getAttribute("expiringMemberCount");
Integer maintenanceCount = (Integer) request.getAttribute("maintenanceCount");
List<String[]> paymentDetails = (List<String[]>) request.getAttribute("paymentDetails");
List<String[]> expiringMemberTypeSummary = (List<String[]>) request.getAttribute("expiringMemberTypeSummary");
List<String[]> maintenanceStatusSummary = (List<String[]>) request.getAttribute("maintenanceStatusSummary");
String reportTitle = "weekly".equalsIgnoreCase(period) ? "Weekly Report" : "Monthly Report";
%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><%= reportTitle %> | FitCore</title>
<link rel="stylesheet" href="<%= request.getContextPath() %>/css/report.css">
</head>
<body>
<div class="sidebar no-print">
    <div class="logo">FitCore</div>
    <div class="menu">
        <a href="<%= request.getContextPath() %>/DashboardServlet">Dashboard</a>
        <a href="<%= request.getContextPath() %>/MemberServlet?action=list">Members</a>
        <a href="<%= request.getContextPath() %>/PaymentController?action=list">Payments</a>
        <a href="<%= request.getContextPath() %>/PromotionServlet?action=list">Promotions</a>
        <a href="<%= request.getContextPath() %>/EquipmentServlet">Equipment</a>
        <a href="<%= request.getContextPath() %>/MaintenanceServlet?action=list">Maintenance</a>
        <a href="<%= request.getContextPath() %>/ReportServlet" class="active">Reports</a>
        <a href="<%= request.getContextPath() %>/StaffServlet?action=list">Staff</a>
    </div>
    <div class="logout"><a href="<%= request.getContextPath() %>/LogoutServlet">Logout</a></div>
</div>

<div class="main">
    <div class="header no-print">
        <div><h1>Reports</h1><p>Generate weekly or monthly gym performance reports.</p></div>
    </div>

    <div class="filter-card no-print">
        <form action="<%= request.getContextPath() %>/ReportServlet" method="get">
            <div class="field">
                <label for="period">Report Type</label>
                <select id="period" name="period">
                    <option value="weekly" <%= "weekly".equals(period) ? "selected" : "" %>>Weekly</option>
                    <option value="monthly" <%= "monthly".equals(period) ? "selected" : "" %>>Monthly</option>
                </select>
            </div>
            <div class="field">
                <label for="anchorDate">Reference Date</label>
                <input id="anchorDate" type="date" name="anchorDate" value="<%= anchorDate %>" required>
            </div>
            <button type="submit" class="btn generate">Generate Report</button>
            <button type="button" class="btn print" onclick="window.print()">Print Report</button>
        </form>
    </div>

    <div class="report-sheet">
        <div class="report-heading">
            <div>
                <div class="report-logo">FitCore</div>
                <h2><%= reportTitle %></h2>
                <p>Reporting period: <strong><%= startDate %></strong> to <strong><%= endDate %></strong></p>
            </div>
            <div class="report-meta">
                <p><strong>Generated:</strong> <%= generatedDate %></p>
                <p><strong>Generated by:</strong> <%= staffName == null ? "Staff" : staffName %></p>
            </div>
        </div>

        <div class="summary-grid">
            <div class="summary-card"><span>Total Revenue</span><strong>RM <%= String.format("%.2f", totalRevenue == null ? 0.0 : totalRevenue) %></strong></div>
            <div class="summary-card"><span>Payment Transactions</span><strong><%= paymentCount == null ? 0 : paymentCount %></strong></div>
            <div class="summary-card"><span>Memberships Expiring</span><strong><%= expiringMemberCount == null ? 0 : expiringMemberCount %></strong></div>
            <div class="summary-card"><span>Maintenance Records</span><strong><%= maintenanceCount == null ? 0 : maintenanceCount %></strong></div>
        </div>

        <div class="two-column">
            <section class="report-section">
                <h3>Membership Expiry by Type</h3>
                <table><thead><tr><th>Member Type</th><th>Total</th></tr></thead><tbody>
                <% if (expiringMemberTypeSummary == null || expiringMemberTypeSummary.isEmpty()) { %>
                    <tr><td colspan="2" class="empty">No memberships expire in this period.</td></tr>
                <% } else { for (String[] row : expiringMemberTypeSummary) { %>
                    <tr><td><%= row[0] %></td><td><%= row[1] %></td></tr>
                <% }} %>
                </tbody></table>
            </section>

            <section class="report-section">
                <h3>Maintenance by Status</h3>
                <table><thead><tr><th>Status</th><th>Total</th></tr></thead><tbody>
                <% if (maintenanceStatusSummary == null || maintenanceStatusSummary.isEmpty()) { %>
                    <tr><td colspan="2" class="empty">No maintenance records in this period.</td></tr>
                <% } else { for (String[] row : maintenanceStatusSummary) { %>
                    <tr><td><%= row[0] %></td><td><%= row[1] %></td></tr>
                <% }} %>
                </tbody></table>
            </section>
        </div>

        <section class="report-section payment-report">
            <h3>Payment Details</h3>
            <div class="table-wrap">
                <table>
                    <thead><tr><th>ID</th><th>Date</th><th>Member</th><th>Total Amount</th><th>Paid Amount</th><th>Method</th><th>Staff</th></tr></thead>
                    <tbody>
                    <% if (paymentDetails == null || paymentDetails.isEmpty()) { %>
                        <tr><td colspan="7" class="empty">No payments found for this period.</td></tr>
                    <% } else { for (String[] row : paymentDetails) { %>
                        <tr><td><%= row[0] %></td><td><%= row[1] %></td><td><%= row[2] %></td><td>RM <%= row[3] %></td><td>RM <%= row[4] %></td><td><%= row[5] %></td><td><%= row[6] %></td></tr>
                    <% }} %>
                    </tbody>
                </table>
            </div>
        </section>
        <div class="report-footer">End of <%= reportTitle.toLowerCase() %></div>
    </div>
</div>
</body>
</html>
